# Generated by Django 5.1.2 on 2024-10-31 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LodgeitApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LodgeitApi.company'),
        ),
    ]
